### ISSUE TITLE
Add mpf.__format__() dunder methods

### ISSUE THREAD

**Issue by ThomasA** [mpmath/mpmath#337]
I am struggling with the conversion of a script written for Python 2.7 to Python 3 (PS: I know Python 3 still understands the old formatting syntax, but I would like to convert to the new formatting syntax as well). Consider the following example (IPython with output):

    In [1]: import mpmath
    
    In [2]: value = mpmath.mp.mpf('1.0')
    
    In [3]: print('%10.0f' % value)
             1
    
    In [4]: print('{:10.0f}'.format(value))
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-4-f8a6817daeeb> in <module>()
    ----> 1 print('{:10.0f}'.format(value))

Is there a sensible fix for this?

I have tried:

     print('{:10s}'.format(mpfloat.nstr(value)))

instead, but I cannot seem to figure out how to configure `nstr` to behave like line 3 above. The latter seems to perform rounding of some numbers that the former does not...

**Comment by skirpichev** [comment]
> I know Python 3 still understands the old formatting syntax

Unfortunately, mpmath types can't be formatted with the old formatting syntax.  Your above examples works because implicit conversion to float.  But CPython floats have only 53 bits of precision, so:
```pycon
>>> float(mpf(2)**2000)
inf
```

> Is there a sensible fix for this?

Yes, provide support for the new formatting syntax.  Meanwhile you can convert mpf objects (using as_integer_ratio() method) either to the CPython's Fraction type or to the gmpy2's mpfr type.  Both types support new formatting.  The mpfr type additionally supports different rounding modes:
```pycon
>>> "{0:15.3Uf}".format(mpfr("1.23456"))
'          1.235'
>>> "{0:15.3Df}".format(mpfr("1.23456"))
'          1.234'
```

Or use ``nstr()``.

> I cannot seem to figure out how to configure nstr to behave like line 3 above

You can't drop ``.0`` in the ``nstr()`` output.  Use ``nint()`` to get nearest integer.

**Comment by skirpichev** [comment]
Ok, now almost all is finished.

Work in progress:
* https://github.com/mpmath/mpmath/pull/841
* https://github.com/mpmath/mpmath/issues/837

"new style" formatting support also lacks documentation.

**Comment by skirpichev** [comment]
@javierelpianista, I think this can be closed by the documentation pr.
