### ISSUE TITLE
bernpoly behaviour at infinity with 0 imaginary component

### ISSUE THREAD

**Issue by cbm755** [mpmath/mpmath#471]
Good:
```
>>> inf = float('inf')
>>> mpmath.bernpoly(3, inf)                                                        
mpf('+inf')

>>> mpmath.bernpoly(4, inf)                                                        
mpf('+inf')
```

Now how about complex with 0 imag part?  This seems ok:
````
>>> bernpoly(4, complex(inf, 0))
mpc(real='+inf', imag='0.0')
```
But:
```
>>> bernpoly(3, complex(inf, 0))
mpc(real='nan', imag='nan')
````
This isn't wrong per se if you think of `complex(..., 0)` as a very small negative part.

Do we care?  Correct behaviour at real infinity is very nice property but maybe exactly what happens for `complex(..., 0)` is less important?

**Comment by skirpichev** [comment]
Ah, that happens because of specialized code:
https://github.com/mpmath/mpmath/blob/cf98bcf07d7d6ef8ebfc0575276107aac46519b9/mpmath/functions/zeta.py#L291-L295

```pycon
z = mpc(inf, 0); z*(z*(z-1.5)+0.5)
mpc(real='nan', imag='nan')
>>> z**3
mpc(real='inf', imag='0.0')
```

This is slightly better in C, because it complex arithmetic has special rules for real operands:
```
$ cat a.c
#include <complex.h>
#include <math.h>
#include <stdio.h>
int main(void)
{
    double complex z = CMPLX(INFINITY, 0);
    z = z*(z*(z-1.5)+0.5);
    printf("%lf%+lfj\n", creal(z), cimag(z));
    return 0;
}
$ gcc a.c -std=c17 -Wpedantic -lm && ./a.out
inf-nanj
```

https://github.com/mpmath/mpmath/issues/805 might help here.  But simplest solution would be moving handling all special cases (inf/nans) up.
