### ISSUE TITLE
make releases clear 

### ISSUE THREAD

**Issue by dimpase** [mpmath/mpmath#584]
At the moment the "latest" release on GH is quite old, older than 1.2.0 (advertised on mpmath.org as "latest")

And what is the status of 1.2.1? Is it the real latest? A pre-release?

**Comment by rocky** [comment]
To try to be clear on the various inconsistencies. There are releases listed in:

* [PyPi](https://pypi.org/project/mpmath/) 1.2.1 from Feb 2021
* [Github releases](https://github.com/fredrik-johansson/mpmath/releases) 1.0.0 (Nov 2018)
* [Github README.rst](https://github.com/fredrik-johansson/mpmath/blob/master/README.rst) PyPI badge is 1.2.1 but in the text the release history goes only to 1.1.0. But starts before the earliest version in tags below. I would suggest removing this from README.rst. I'd be happy to put in a PR for this.
* [Github tags](https://github.com/fredrik-johansson/mpmath/tags) this goes back to 0.7
* [mpmath.org](https://mpmath.org/) Lists 1.2.0

**Comment by skirpichev** [comment]
@fredrik-johansson, I can automate Github releases [like I did](https://github.com/diofant/diofant/releases) for the [Diofant](https://github.com/diofant/diofant/releases): a draft release (private, you must approve it to be shown) will be created for every tag push.  OR it may be a public release...  *.tgz and *.whl will be identical on PyPI and releases page.

No idea how to automate mpmath.org update (but I'm sure, it's possible too).  Perhaps, you can just point to other resources (PyPI, Github releases) to provide packages/sources.  readthedocs.org could be used to keep docs.

> I would suggest removing this from README.rst

@rocky, that does make sense.  Maybe, CHANGES could be kept with docs somewhere.

**Comment by rocky** [comment]
For what it is worth, the process I use is:

Create a ChangeLog: 
 ```
$ git log --pretty --numstat --summary | git2cl > ChangeLog
```

From that extract notes for `NEWS.md`. Alternatively as you make significant commits and PR's update NEWS.md as you go along.  

From `NEWS.md`,  add the most recent section to the github releases. [Github releases](https://github.com/fredrik-johansson/mpmath/releases/new).   Markdown for NEWS is good if you use github releases since that handles markdown. For Python-based projects RsT is nice to have but that means converting to markdown if using  github releases.

**Comment by rocky** [comment]
Do get the latest release on mpmath.org, why not just use the PyPI badge https://img.shields.io/pypi/v/mpmath.svg ? 
(I think the badge also comes in other forms.)

**Comment by rocky** [comment]
@fredrik-johansson I read in https://groups.google.com/g/mpmath/c/v8VjGgR1HH4/m/2PuqlB1sAQAJ that since last September you've been looking for someone to help with maintaining this repository. 

While, I can't commit to anything long term, in the short term I would be happy to do the largely mechanical steps outlined to address this particular issue.

**Comment by skirpichev** [comment]
@rocky, feel free to provide a PR.  Nobody will stop you.

**Comment by rocky** [comment]
@skirpichev For some of the things I like changing README.rst a PR will do. Oh, and where is the source to https://mpmath.org ?

Hwever for updating https://github.com/fredrik-johansson/mpmath/releases you need serious admin access.

**Comment by skirpichev** [comment]
On Fri, Apr 02, 2021 at 02:49:29AM -0700, R. Bernstein wrote:
>    Oh, and where is the source to [2]https://mpmath.org ?

No idea.  Perhaps, on a private github repo.  You can't change that
stuff.  But you can proofread everything here and suggest some changes.

>    Hwever for updating
>    [3]https://github.com/fredrik-johansson/mpmath/releases you need serious
>    admin access.

I'll make a PR for this.  Lets see if it will be accepted.
